BIN = ./mainTest

SRC_BIN = \
	mainTest.C\
	

SRC_ALL = \
	${SRC_COM}\
	${SRC_BIN}

HEAD_ALL = ${SRC_BIN:.C:.h}

OBJ_BIN = ${SRC_BIN:.C=.o}

UNIFRAMEINC = \
	-I.\
	-I../../include\
	-I../../include/comserv\
	-I../../include/msg\
	-I../../include/kernel\
	-I../../include/task\
	-I../../include\
	-I../../facility/psamqtt-wangpan\
	-I../../facility/interface/mqtt

CFLAGS = -g ${UNIFRAMEINC} -Wno-deprecated -std=c++11


exe: ${BIN}

all: ${BIN}

${BIN}: ${OBJ_BIN}
	g++ -o ${BIN} ${OBJ_BIN} -L../../_bin/lib -lxframe -lcrypto \
	-lmysqlclient_r -lhiredis -lmsglib_mqtt ${SYSLIB}
	#	refcheck .

.C.o:   ${SRC_ALL} ${HEAD_ALL}
	g++ -o $@ -c ${CFLAGS}  $<

clean:
	rm -f ${BIN} ${OBJ_BIN}

DLLDIR = ../../_bin
install:
	mkdir -p ${DLLDIR}/
	cp ${BIN} ${DLLDIR}/
